import { Inter } from 'next/font/google'
import Header from '../components/Header';
import { ClerkProvider } from "@clerk/nextjs";
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "AXIS'24",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
    </ClerkProvider>
  )
}
